language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpunit --coverage-text --coverage-clover=coverage.clover; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then phpunit; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
